version: "3"
services:
  identidock:
    image: <aws-account-region>.dkr.ecr.ap-northeast-1.amazonaws.com/identidock:1.0
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - /app
    depends_on:
      - "dnmonster"
      - "redis"
    logging:
      driver: awslogs
      options:
        awslogs-group: identidock
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: identidock

  dnmonster:
    image: amouat/dnmonster:1.0

  redis:
    image: redis

