version: "2"
services:
  identidock:
    build: .
    expose:
      - "9090"
    environment:
      ENV: PROD
    links:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster:1.0

  redis:
    image: redis

